### ISSUE TITLE
Allow uploading multiple `webpack-stats.json` files

### ISSUE THREAD

**Issue by marekdedic** [relative-ci/agent-upload-artifact-action#1]
Hi,
I have a build that produces multiple outputs in parallel. It therefore produces multiple `webpack-stats.json` files - I can give them different names, but they are separate files. Is there any way to use all of them?

**Comment by vio** [comment]
hey @marekdedic!  The action is just a simple wrapper on top of the standard `upload-artifact`.  Here it is an example of how you can use it with multiple files: https://relative-ci.com/documentation/setup/agent/github-action/#example-for-workflow_run-event

Also, you can use your own config to: 
1. upload all the files into one single artifact
2. download on the workflow where you want to send them 
3. pass each file to the agent action

Feel free to reopen if you still have questions or challenges ;)

**Comment by marekdedic** [comment]
Hi,
thanks, I have tried to set this up. I can upload 2 different `webpack-stats` files into an artifact, that works fine, but when I then try to pass them to `agent-action`, the second run fails - see https://github.com/marekdedic/imagelightbox/actions/runs/8849507776/job/24301671194

How can I use 2 `webpack-stats` files for one commit in one project?

**Comment by vio** [comment]
@marekdedic i tried to replicate the error on a fork, but both artifacts were sent successfully:

<img width="1262" alt="image" src="https://github.com/relative-ci/agent-upload-artifact-action/assets/13300/7aeaecc4-b50c-42fe-a17f-21d43f9a43e2">

https://github.com/vio/imagelightbox/actions/runs/9390942810/job/25862045203

I had to merge the PR because workflow triggered on `workflow_run` run in the [context of the base branch](https://relative-ci.com/documentation/setup/agent/github-action/#about-workflows-triggered-by-forked-repositories-and-insecure-workflowsdependabot-updates). 

If you manage to try again, i recommend setting `debug: true` on `relative-ci/agent-action` step. 

---

Also, a related note regarding the project setup, when sending webpack-stats from multiple compilations, you want to send them to different RelativeCI projects. Because they are processed as consecutive jobs on the same project, the comparisons with the baselines are going to be incorrect: https://app.relative-ci.com/projects/wWO3RTZFd2XZmAbs0rjg/jobs.

- https://relative-ci.com/documentation/setup/agent/github-action/#example-for-workflow_run-event
- https://github.com/relative-ci/roadmap/issues/30#issuecomment-964397293

**Comment by marekdedic** [comment]
Ok, I tried splitting the projects and merging the PR and that helped.

It's still not that ergonomic, having to have multiple RelativeCI projects, but that's also caused by the build system not supporting multiple outputs...

Thanks for the help, closing the issue :)

**Comment by vio** [comment]
We are planning to improve the multiple builds soon as part of the superprojects: https://github.com/relative-ci/roadmap/issues/48 ;)

**Comment by marekdedic** [comment]
Great, looking forward to that :)
